---
title: "Clinical Experience"
output:
  html_document:
    df_print: paged
    number_sections: no
    toc: yes
    toc_float:
      collapsed: false
      smooth_scroll: false
---


<a href="Project_Experience.pdf#" class="download" title="Download Project Experience as PDF">Download Project Experience</a>

 


## Oncology

|     Nr.    |     Condition   or disease                                                                                                                                          |     Phase          |     Site                         |
|:-----------|:--------------------------------------------------------------------------------------------------------------------------------------------------------------------|:-------------------|:---------------------------------|
| 1          |     [Selected advanced/metastatic solid tumors](https://clinicaltrials.gov/ct2/show/NCT04234113)                                                                    |     Phase   1      |     12   Sites                   |
| 2          |     [Acute Myeloid Leukemia](https://clinicaltrials.gov/ct2/show/NCT03516760)                                                                                       |     Phase   1      |     7   Sites                    |
| 3          |     [Non-small Cell Lung Cancer     Prostate Cancer     Renal Cancer     Transitional Cell Carcinoma](https://clinicaltrials.gov/ct2/show/NCT03927573)              |     Phase   1/2    |     5   Sites                    |
| 4          |     [Locally Advanced Unresectable Pancreatic Adenocarcinoma](https://www.clinicaltrials.gov/ct2/show/NCT04098432)                                                  |     Phase   1      |     4   Sites                    |
| 5          |     [AML and MDS patients failing or being refractory to   hypomethylating agent (HMA)-based treatment](https://classic.clinicaltrials.gov/ct2/show/NCT05583552)    |     Phase   2      |     12   Sites                   |
| 6          |     [Triple Negative Breast Cancer](https://clinicaltrials.gov/ct2/show/NCT02032277)                                                                                |     Phase   2      |     158   Sites                  |
| 7          |     [Breast Cancer](https://clinicaltrials.gov/ct2/show/NCT02682693?term=GeparX&draw=2&rank=1)                                                                      |     Phase   2      |     Multiple in Germany          |
| 8          |     [Breast Cance](https://clinicaltrials.gov/ct2/show/NCT02685059?term=GeparNuevo&draw=2&rank=1)                                                                   |     Phase   2      |     Multiple in Germany          |
| 9          |     [Cutaneous melanoma](https://www.melagenix.info/about-melagenix)                                                                                                |     Phase   3      |     Multiple in US and Europe    |
| 10         |     [Stage I-III melanoma](https://www.melagenix.info/for-healthcare-professionals)                                                                                 |     Phase   3      |     Multiple                     |
| 11         |     [Cervical Intraepithelial Neoplasia Grade 2/3](https://clinicaltrials.gov/ct2/show/NCT04484415)                                                                 |     Phase   3      |     Multiple in China            |
| 12         |     [Breast Cancer](https://clinicaltrials.gov/ct2/show/NCT01864746)                                                                                                |     Phase   3      |     11 Sites                     |
| 13         |     [Breast Cancer](https://clinicaltrials.gov/ct2/show/NCT02125344?term=GeparOcto&draw=2&rank=1)                                                                   |     Phase   3      |     Multiple in Germany          |
| 14         |     [Multiple Solid Tumor](https://classic.clinicaltrials.gov/ct2/show/NCT03993873)                                                                                 |     Phase   2      |     24 Sites                     |


## Ophthalmology

| Nr. |     Condition   or disease                                                            |     Phase      |     Site                       |
|:----|:--------------------------------------------------------------------------------------|:---------------|:-------------------------------|
| 15  |     [Primary Open-angle Glaucoma](https://clinicaltrials.gov/ct2/show/NCT03651336)    |     PMCF       |     4 Sites                    |
| 16  |     [Presbyopia](https://clinicaltrials.gov/ct2/show/NCT03790592)                     |     PMCF       |     1 Site                     |
| 17  |     Presbyopia                                                                        |     PMA        |     Multiple                   |
| 18  |     [Cataract](https://clinicaltrials.gov/ct2/show/NCT03839420)                       |     PMCF       |     Multiple in Germany        |
| 19  |     [Cataract Senile](https://clinicaltrials.gov/ct2/show/NCT04998409)                |     PMCF       |     Multiple in Germany        |
| 20  |     [Cataract Senile](https://www.clinicaltrials.gov/ct2/show/NCT04789538)            |     PMCF       |     Multiple in Germany        |
| 21  |     [Cataract Senile](https://clinicaltrials.gov/ct2/show/NCT04793789)                |     PMCF       |     Multiple in Germany        |
| 22  |     [Cataract Senile](https://clinicaltrials.gov/ct2/show/NCT04907500)                |     PMCF       |     Multiple in Romania        |
| 23  |     [Cataract Senile](https://clinicaltrials.gov/ct2/show/NCT04545671)                |     PMCF       |     Multiple in Germany        |
| 24  |     [Cataract Senile](https://clinicaltrials.gov/ct2/show/NCT05201027)                |     PMCF       |     Multiple in El Salvador    |
| 25  |     [Cataract Senile](https://www.clinicaltrials.gov/ct2/show/NCT04252716)            |     PMCF       |     Multiple in Germany        |
| 26  |     Cataract Senile OVD-PROMIZ                                                        |     PMCF       |     Multiple in Germany        |
| 27  |     Cataract Cataract-VirtIOL                                                         |     PMA        |     Multiple in Germany        |
| 28  |     Survey-RT Decalin                                                                 |     Surgery    |     Survey Study               |


## Allergology

| Nr. |     Condition   or disease                                                                                      |     Phase        |     Site                       |
|:----|:----------------------------------------------------------------------------------------------------------------|:-----------------|:-------------------------------|
| 29  |     [Allergic rhinoconjunctivitis](https://www.clinicaltrialsregister.eu/ctr-search/trial/2017-005079-21/DE)    |     Phase   2    |     Multiple                   |


## Infections and Infestations Disorders

### COVID-19

| Nr. |     Condition   or disease                                                                                                                                 |     Phase        |     Site                       |
|:----|:-----------------------------------------------------------------------------------------------------------------------------------------------------------|:-----------------|:-------------------------------|
| 30  |     [COVID-19](https://clinicaltrials.gov/ct2/show/NCT04776044)                                                                                            |     Phase   2    |     40 Sites                   |
| 31  |     [COVID-19](https://clinicaltrials.gov/ct2/show/NCT04750759)                                                                                            |     Phase   2    |     Multiple in Germany        |
| 32  |     [COVID-19](https://ctkbiotech.com/product/onsite-covid-19-ag-rapid-test/)                                                                              |     PMCF         |     1 Site                     |
| 33  |     [COVID-19](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9095852/)                                                                                      |     NIS          |     Observation Study          |
| 34  |     [COVID-19](https://www.baden-wuerttemberg.de/de/service/alle-meldungen/meldung/pid/studie-zum-moeglichen-infektionsrisiko-im-nahverkehr-gestartet/)    |     NIS          |     Observation Study          |



### HIV/AIDS

| Nr. |     Condition   or disease                                                                                                                                 |     Phase        |     Site                       |
|:----|:-----------------------------------------------------------------------------------------------------------------------------------------------------------|:-----------------|:-------------------------------|
| 35  |     [Human immunodeficiency virus infection and acquired   immunodeficiency syndrome (HIV/AIDS)](https://clinicaltrials.gov/ct2/show/NCT03094507)          |     Phase   1    |     1   Site                   |


### Gynecology

| Nr. |     Condition   or disease                                                                                                                                 |     Phase        |     Site                       |
|:----|:-----------------------------------------------------------------------------------------------------------------------------------------------------------|:-----------------|:-------------------------------|
| 36  |     [Bacterial vaginosis](https://www.clinicaltrialsregister.eu/ctr-search/search?query=2020-002489-15)          |     PMCF    |     Multiple                 |


## Immunology

| Nr. |     Condition   or disease                                                                                                                                 |     Phase        |     Site                       |
|:----|:-----------------------------------------------------------------------------------------------------------------------------------------------------------|:-----------------|:-------------------------------|
| 37  |     [Acute Graft Versus Host Disease in Intestine     Steroid Refractory GVHD]( https://clinicaltrials.gov/ct2/show/NCT04769895)                           |     Phase   3    |     39   Sites                 |
| 38  |     [Active Rheumatoid Arthritis](https://www.clinicaltrialsregister.eu/ctr-search/search?query=2020-003955-14)                                            |     Phase   2    |     1   Site                   |
| 39  |     Reconstitution of a severely impaired immune system                                                                                                    |     Phase   1    |     1   Site                   |

## Endocrinology

| Nr. |     Condition   or disease                                                               |     Phase      |     Site        |
|:----|:-----------------------------------------------------------------------------------------|:---------------|:----------------|
| 40  |     [Congenital Adrenal Hyperplasia](https://clinicaltrials.gov/ct2/show/NCT03669549)    |     Phase 2    |     11 Sites    |
| 41  |     [Osteoporosis Bone Loss](https://clinicaltrials.gov/ct2/show/NCT04934072)            |     Phase 3    |     71 Sites    |


## Hepatology

| Nr. |     Condition   or disease                                                                                        |     Phase       |     Site        |
|:----|:------------------------------------------------------------------------------------------------------------------|:----------------|:----------------|
| 42  |     [Primary Biliary Cholangitis     Liver Stiffness](https://classic.clinicaltrials.gov/ct2/show/NCT05014672)    |     Phase 2b    |     80 Sites    |



## Neurology

| Nr. |     Condition   or disease                                         |     Phase        |     Site          |
|:----|:-------------------------------------------------------------------|:-----------------|:------------------|
| 43  |     [Epilepsy](https://clinicaltrials.gov/ct2/show/NCT02408549)    |     Phase   3    |     87   Sites    |
| 44  |     Serious mental illness                                         |     PMCF         |     1   Site      |

## Dermatology

| Nr. |     Condition   or disease                                                                                                 |     Phase        |     Site                     |
|:----|:---------------------------------------------------------------------------------------------------------------------------|:-----------------|:-----------------------------|
| 45  |     Alopecia                                                                                                               |     Phase   4    |     Decentralized   Study    |
| 46  |     [Thermal Burns](https://clinicaltrials.gov/ct2/show/NCT02148705)                                                       |     Phase   3    |     29   Sites               |
| 47  |     [Aesthetic Medicine Skin perception](https://www.clinicaltrialsregister.eu/ctr-search/search?query=2020-001318-39)    |     Phase   2    |     1   Site                 |
| 48  |     [Bilateral Blepharospasm](https://clinicaltrials.gov/ct2/show/NCT01896895)                                             |     Phase   3    |     11   Sites               |
| 49  |     [Venous Leg Ulcer](https://clinicaltrials.gov/ct2/show/NCT04192123)                                                    |     PMCF         |     1   Site                 |
| 50  |     [Venous Leg Ulcer](https://clinicaltrials.gov/ct2/show/NCT04902651)                                                    |     PMCF         |     3   Sites                |

## Urology

| Nr. |     Condition   or disease      |     Phase    |     Site          |
|:----|:--------------------------------|:-------------|:------------------|
| 51  |     Removal of kidney stones    |     PMCF     |     10   Sites    |
|     |                                 |              |                   |

## Pain

| Nr. |     Condition   or disease                                             |     Phase        |     Site        |
|:----|:-----------------------------------------------------------------------|:-----------------|:----------------|
| 52  |     [Chronic Pain](https://clinicaltrials.gov/ct2/show/NCT04198558)    |     Phase   1    |     1   Site    |
| 53  |     Complaints                                                         |     PMCF         |     Multiple    |
