---
title: "CV"
---

<a href="https://github.com/Zehuibai/Zehuibai.github.io/blob/master/CV.pdf#" class="download" title="Download CV as PDF">Download CV</a>			

# BERUFSERFAHRUNG

```{r}
library(vitae)
library(tibble)

tribble(
  ~Year, ~Type, ~Desc,
  "03/2020-Bisher",     "Hiwi in GCP-Service, Abteilung Clinical Data Management - Statistics", "Umgang mit dem Durchführen von SAP, primäre Endpunkt-, sekundäre Endpunkt- und Sicherheitsanalysen und Reports in SAS",
  "03/2020-Bisher",     "Masterarbeit beim BIPS, Abteilung Biometrie und EDV", "Arbeitsthema: Random Forests for Multiple Imputation of Missing Data in IDEFICS study",
  "08/2019-09/2019",    "Praktikum beim BIPS, Abteilung Biometrie und EDV", "Umgang mit dem Datenmanagement in R und SAS, deskreptive Analysen und Reports in SAS, Multiple Imputation fehlender Werte und Diagnose der Imputationsergebnisse",
  "06/2016-09/2016",     "Praktikum in Pegasus Medical Devices Co. (Biomedizinisches Unternehmen in China)", "Umgang mit biomedizinischer Beratung und die Analyse von Verkaufsdaten mit SAS"
) %>% 
  brief_entries(
    glue::glue("{Type}"),
    Year, 
    Desc
  )
```




 
# AUSBILDUNG

```{r}
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  "M.Sc. Medical Biometry/Biostatistics", "10/2018-Bisher", "Universität Bremen", "Deutschland",
  "B.Sc. Bioingenieurwesen (Hauptfach)", "08/2013-07/2017", "Universität Tianjin", "China",
  "B.Sc. Rechtswissenschaft (Nebenfach)", "08/2014-07/2017", "Universität Tianjin", "China"
) %>% 
  detailed_entries(Degree, Year, Institution, Where)

tribble(
  ~Year, ~Type, ~Desc,
  "06/2016-10/2016", "Ausbildung zum Senior Ernährungsberater", " International Professional Certification Center, China"
) %>% 
  brief_entries(
    glue::glue("{Type}"),
    Year, 
    Desc
  )
```

# KENNTNISSE UND INTERESSEN

```{r}
tribble(
  ~Year, ~Type, ~Desc,
  "Fremdsprachen",     "Deutsch (fließend), Englisch (fließend), Chinesisch (Muttersprache)", "", 
  "IT",                "SAS (Kompetent: Datenmanagement, Datenanalyse, Erstellung statistischer Berichte usw.)","",
  "",                  "R (Kompetent: Machine Learning, Datenmanagement, Visualisierung, Multiple Imputation, GLM, Multiple Vergleiche, Survivalanalyse, Markdown usw.)", "",
  "",                  "LaTeX (Grundstufe)","",
  "",                  "MS-Office (Gut)","",
  "Hobbys",            "Ölgemälde, Oper, klassische Musik", ""
) %>% 
  brief_entries(
    glue::glue("{Type}"),
    Year, 
    Desc
  )
```