---
title: "Welcome to my weisite"
date: "Last Update `r Sys.Date()`"
output:
  prettydoc::html_pretty:
    theme: architect
    highlight: github
---

# Introduction

As a biostatistician, providing statistical input into Phase I - IV and medical device clinical trial development for over 50 international clinical trials in areas such as Oncology, Ophthalmology, Respiratory Disease, Chronic Pain, Allergology, Wound Care, Aesthetic Medicine, COVID19, and more, while utilizing a flexible range of statistical tools, including SAS and R programming. Anchored in solid statistical knowledge and an aggressive attitude, while also maintaining a conscientious and responsible work ethic to guarantee high-quality deliverables.

# Clinical Trial Experience

<a href="https://github.com/Zehuibai/Zehuibai.github.io/blob/master/Project_Experience.pdf#" class="download" title="Download Project Experience as PDF">Download Project Experience</a>			


## Oncology

|     Nr.    |     Condition   or disease                                                                                                                                          |     Phase          |     Site                         |
|------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------------|----------------------------------|
| 1          |     [Selected advanced/metastatic solid tumors](https://clinicaltrials.gov/ct2/show/NCT04234113)                                                                    |     Phase   1      |     12   Sites                   |
| 2          |     [Acute Myeloid Leukemia](https://clinicaltrials.gov/ct2/show/NCT03516760)                                                                                       |     Phase   1      |     7   Sites                    |
| 3          |     [Non-small Cell Lung Cancer     Prostate Cancer     Renal Cancer     Transitional Cell Carcinoma](https://clinicaltrials.gov/ct2/show/NCT03927573)              |     Phase   1/2    |     5   Sites                    |
| 4          |     [Locally Advanced Unresectable Pancreatic Adenocarcinoma](https://www.clinicaltrials.gov/ct2/show/NCT04098432)                                                  |     Phase   1      |     4   Sites                    |
| 5          |     [AML and MDS patients failing or being refractory to   hypomethylating agent (HMA)-based treatment](https://classic.clinicaltrials.gov/ct2/show/NCT05583552)    |     Phase   2      |     12   Sites                   |
| 6          |     [Triple Negative Breast Cancer](https://clinicaltrials.gov/ct2/show/NCT02032277)                                                                                |     Phase   2      |     158   Sites                  |
| 7          |     [Breast Cancer](https://clinicaltrials.gov/ct2/show/NCT02682693?term=GeparX&draw=2&rank=1)                                                                      |     Phase   2      |     Multiple in Germany          |
| 8          |     [Breast Cance](https://clinicaltrials.gov/ct2/show/NCT02685059?term=GeparNuevo&draw=2&rank=1)                                                                   |     Phase   2      |     Multiple in Germany          |
| 9          |     [Cutaneous melanoma](https://www.melagenix.info/about-melagenix)                                                                                                |     Phase   3      |     Multiple in US and Europe    |
| 10         |     [Stage I-III melanoma](https://www.melagenix.info/for-healthcare-professionals)                                                                                 |     Phase   3      |     Multiple                     |
| 11         |     [Cervical Intraepithelial Neoplasia Grade 2/3](https://clinicaltrials.gov/ct2/show/NCT04484415)                                                                 |     Phase   3      |     Multiple in China            |
| 12         |     [Breast Cancer](https://clinicaltrials.gov/ct2/show/NCT01864746)                                                                                                |     Phase   3      |     11 Sites                     |
| 13         |     [Breast Cancer](https://clinicaltrials.gov/ct2/show/NCT02125344?term=GeparOcto&draw=2&rank=1)                                                                   |     Phase   3      |     Multiple in Germany          |
| 14         |     [Multiple Solid Tumor](https://classic.clinicaltrials.gov/ct2/show/NCT03993873)                                                                                 |     Phase   2      |     24 Sites                     |

