---
title: 'Statistical knowledge mind map'
author: "Zehui Bai"
date: 'Stand: `r format(Sys.time(), "%F %H:%M Uhr")`'
output:
  html_document:
    df_print: paged
    number_sections: No
    toc: yes
    toc_float: yes
  word_document:
    toc: yes
fontsize: 10pt
editor_options:
  chunk_output_type: console
colorlinks: yes
---

```{r setup, include=FALSE, echo = FALSE,message = FALSE, error = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE)

# load package
```

 
 

# Multiple Imputation
## Joint modeling
## Fully conditional specification
## Bayesian multiple imputation
## Predictive mean matching
## Random forests for multiple imputation 

# Meta Analysis
## Meta-analysis of continuous outcome
## Fixed effect model
## Inverse variance method
## Weighted sum of z-scores
## Random effects model 
## Meta-analysis of binary outcome data

#  Time Serise Analysis
## Autoregressive processes
## Moving Average processes
## Autoregressive moving average (ARMA) model
## Integrated autoregressive moving average (ARIMA) model



#  Machine Learning Model
## Decision tree model
## Random Forest
## Cubist model
## Linear discriminant analysis
## Support vector machine
## K-nearest neighbors
## Hierarchical clustering
## K-means clustering
## Principal component analysis