---
title: 'Statistical knowledge mind map'
author: "Zehui Bai"
date: 'Stand: `r format(Sys.time(), "%F %H:%M Uhr")`'
output:
  html_document:
    df_print: paged
    number_sections: No
    toc: yes
    toc_float: yes
  word_document:
    toc: yes
fontsize: 10pt
editor_options:
  chunk_output_type: console
colorlinks: yes
---

```{r setup, include=FALSE, echo = FALSE,message = FALSE, error = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE)

# load package
```


# Datamanagement and Visualization

## Datamanagement in SAS
### Data step (retain, first.var, array, loop, data NULL...)
### Proc Import
### Proc SQL
### Proc Transpose
### Descriptive statistics
### Macro (%global, %)
### Proc Report and ODS


## Datamanagement in R
### Package readr 
### Package strings
### Package forcats
### Package lubridate
### Package tidyr
### Package reshape2
### Package dplyr
### Descriptive statistics

## Visualization
### Proc Sqplot
### R Package ggplot2 for scatter, dot, gistogram, box, bar, correlation plots...
### R Package mindr for mind maps
### R Package DiagrammeR for flow charts


# Clinical Trial Tasks

## Sample Siza Calculation
### Binomial: Wald, Clopper-Pearson, Wilson score, Bayesian...
### Paired Proportions: McNemar's Z-test 
### Chi-square test
### Test mean (t-test)
### Test odds ratio
### Test correlation
### Multiple test
### Time-To-Event Data (Cox PH)
### Log-Rank Tests for Competing Risks
### Wilcoxon rank-sum test
### Simulation based methods
### Estimation in diagnostic test

## Randomization
### Simple randomization
### Block randomization
### Stratified randomization

## SDTM and ADaM SAS (Basic)
### %make_define
### %make_empty_dataset
### Creates SDTM DTC date
### %Create_STDM_domains
### %Create_ADaM_datase
### Merge supplemental qualifiers
### SDTM DTC to ADaM Date

## Phase I-III Trials Design
### Single ascending dose
### Multiple ascending dose
### Fleming’s Two-Stage design
### Simon’s 2-Stage Design
### Cross-Over Design
### Jonckheere-Terptsra (JT) trend test
### Cochran-Armitage (CA) trend test
### MCP-Mod
### Pigeot Method

## Group sequential Design

## Adaptive sequential Design


# Regression Model

## Linear regression
### Ordinary least squares
### Confidence Intervals for estimates/predictions
### Model diagnostics
### Model selections
### Skewness scale and transfomration
### Interactions and simple slopes analysis
### Collinearity


## Logistic Regression
### ROC and Cutoff analysis
### Binary logit model
### Probit model
### Complementary log-log-model
### Multi-category logit model
### Ordinal cumulative logit model
### Adjacent categories model
### Logit analysis of contingency tables
### Loglinear analysis of contingency tables
### Longitudinal and other clustered data


## Survival Analysis
### Kaplan-Meier estimator
### Nelson-Aalen estimator
### Compare the survival function
### Exponential regression  model
### Weibull regression model
### Accelerated failure time (AFT) model
### Cox proportional hazards model
### Tied or discrete data
### Time-dependent covariates
### Cumulative incidence function for competing risk
### Subdistribution hazard model
### Cause-specific hazard model
### Clustered Events


## Count Data Regression
### Poisson regression
### Negative binomial regression
### Zero-truncated poisson regression model
### Zero-insflated model
### Hurdle models

## Proportion Response Regression
### Beta regression
### Zero-inflated beta regression
### One-inflated beta regression
### Zero-one-inflated beta regression

## Mixed Model Regression
### MLE and REML in Marginal model
### Kackar-Harville/Kendward-Roger correction
### Wald Test
### Likelihood Ratio Test
### Random Slope and Intercept Model with Independent Structure
### Random Slope and Intercept Model with Covariance Structure
### Generalized Estimating Equation  
### Hierarchical (Nested) Regression Model
### Generalized linear mixed model

## Nonparametric Regression
### Loess Regression
### Thin-Plate Smoothing Spline Method
### Nonparametric Generalized Additive Regression
### Ridge Regression
### Lasso Regression
### Elastic net regularization
### Multivariate adaptive regression spline
### Principal component analysis for regression


# Statistic Analysis

## Parametric Test
### Binomial test
### Fisher's Exact Test
### McNemar's test
### Cochran–Mantel–Haenszel Test
### Correlation Test
### Two Sample T-Test
### Normality test 

## ANOVA and Multiple Test
### Balanced One-Way Analysis-of-Variance (ANOVA)
### Unbalanced One-Way ANOVA and Analysis-of-Covariance (ANCOVA)
### Two-Ways ANOVA
### Šidák and Bonferroni
### Schweder-Spjøtvoll p-Value Plot
### Tukey’s Method
### Dunnett’s Two-Sided/One-Sided Comparisons
### Hsu-Nelson Simulation
### Scheffés Method
### Bonferroni-Holm Method
### Šidák-Holm Method
### Step-down Dunnett test

## Non-Parametric Test
### Sign Test for Location Parameter
### Wilcoxon Signed-Rank Test
### Wilcoxon Rank-Sum Test 
### Ansari-Bradley Test
### Kolmogorov-Smirnov Test
### Friedman Rank Test
### Kruskal-Wallis H-Test
### Permutation test

## Multiple Imputation
### Expectation-maximization 
### Joint modeling
### Fully conditional specification
### Bayesian multiple imputation
### Passive imputation
### Predictive mean matching
### Random Forests for Multiple Imputation 

## Meta Analysis
### Meta-analysis of continuous outcome
### Fixed effect model
### Inverse variance method
### Weighted sum of z-scores
### Random effects model 
### Hartung-Knapp Adjustment
### Meta-analysis of binary outcome data
### Meta-Regression

## Time Serise Analysis
### Cyclical or Seasonal Trends
### Cosine Trends
### Autoregressive moving average (ARMA) model


## Machine Learning Model
### Regularization
### Decision tree model
### Random Forest
### Cubist model
### Linear discriminant analysis
### Support vector machine
### K-nearest neighbors
### Hierarchical clustering
### K-means clustering
### Principal component analysis

